version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app
      FLASK_ENV: development

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: human_resources
      POSTGRES_USER: prado
      POSTGRES_PASSWORD: Prado
    ports:
      - "5432:5432"
